---
- name: "Set Archive name fact"
  set_fact:
    prometheus_am_archive: "alertmanager-{{ alertmanager_version }}.{{ prometheus_platform_suffix }}.tar.gz"

- name: "Set Binary url fact"
  set_fact:
    prometheus_am_binary_url: "{{ __prometheus_am_bin_url }}/v{{ alertmanager_version }}/{{ prometheus_am_archive }}"

- name: "Ensure Alert Manager binary exists"
  stat:
    path: "{{ prometheus_path_install }}/alertmanager-{{ alertmanager_version }}.{{ prometheus_platform_suffix }}/alertmanager"
  register: alertmanager_binary_stat

- block:

  - name: "Download Alert Manager binaries"
    get_url:
      url: "{{ prometheus_am_binary_url }}"
      dest: "/tmp/{{ prometheus_am_archive }}"
    retries: 5
    delay: 10

  - name: "Download and expand Alert Manager binaries"
    unarchive:
      src: "/tmp/{{ prometheus_am_archive }}"
      dest: "{{ prometheus_path_install }}"
      owner: "{{ prometheus_user }}"
      group: "{{ prometheus_group }}"
      copy: no

  - name: "Remove Alert Manager archive"
    file:
      path: "/tmp/{{ prometheus_am_archive }}"
      state: absent

  when: not alertmanager_binary_stat.stat.exists

- name: "Ensure files permissions"
  file:
    path: "{{ prometheus_path_install }}"
    state: directory
    recurse: yes
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "go-w"

# - name: "Ensure Prometheus systemd's unit file exists"
#   template:
#     src: "alertmanager.service.j2"
#     dest: "/etc/systemd/system/{{ alertmanager_service_name }}.service"
#   register: alertmanager_service_changed
#
# - name: "Ensure systemd daemon reload"
#   systemd:
#     name: "{{ alertmanager_service_name }}"
#     daemon_reload: yes
#   when: alertmanager_service_changed.changed == True
#
# - name: "Ensure Alert Manager systemd service run at boot time"
#   systemd:
#     name: "{{ alertmanager_service_name }}"
#     enabled: yes
#   notify:
#     - "restart alertmanager service"

- name: "Ensure Alert manager configuration"
  template:
    src: "alertmanager.yml.j2"
    dest: "{{ prometheus_path_config }}/alertmanager.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rw,g=,o="
  notify:
      - "restart alertmanager service"
