---

- name: "Use linux 64bit binaries"
  set_fact:
    prometheus_platform_suffix: "linux-amd64"
  when: 'ansible_userspace_bits == "64"'

- name: "Use linux 32bit binaries"
  set_fact:
    prometheus_platform_suffix: "linux-386"
  when: 'ansible_userspace_bits == "32"'

- name: "Set prometheus daemon directory fact"
  set_fact:
    prometheus_daemon_dir: "{{ prometheus_install_path }}/prometheus-{{ prometheus_version }}.{{ prometheus_platform_suffix }}"
  when: '"prometheus" in prometheus_components'
